# Generated by Django 2.1.5 on 2019-02-20 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 19, 27, 22, 867445, tzinfo=utc)),
        ),
    ]
