# Generated by Django 2.1.5 on 2019-02-20 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playeruser_regtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='time',
            field=models.FloatField(default=7200.0),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 19, 27, 50, 324626, tzinfo=utc)),
        ),
    ]
