# Generated by Django 2.1.7 on 2019-02-20 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190220_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 21, 16, 59, 557933, tzinfo=utc)),
        ),
    ]
