# Generated by Django 2.1.7 on 2019-02-21 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190221_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='currentQs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 19, 44, 5, 276689, tzinfo=utc)),
        ),
    ]
