# Generated by Django 2.1.5 on 2019-02-23 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190221_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 19, 1, 57, 230291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='time',
            field=models.FloatField(default=40.0),
        ),
    ]
