# Generated by Django 2.1.7 on 2019-02-23 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190221_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 20, 44, 31, 103966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='time',
            field=models.FloatField(default=200.0),
        ),
    ]
