# Generated by Django 2.1.7 on 2019-02-28 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190223_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 18, 55, 47, 182333, tzinfo=utc)),
        ),
    ]
