# Generated by Django 2.1.5 on 2019-02-23 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190223_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 19, 22, 38, 293594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='time',
            field=models.DateTimeField(default=200.0),
        ),
    ]
