# Generated by Django 2.1.7 on 2019-03-16 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20190228_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeruser',
            name='currentQs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 16, 37, 51, 839137, tzinfo=utc)),
        ),
    ]
