# Generated by Django 2.1.5 on 2019-02-28 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20190223_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='qtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 51, 14, 783666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 51, 14, 783593, tzinfo=utc)),
        ),
    ]
