# Generated by Django 2.1.5 on 2019-02-28 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20190228_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='currentQs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='qtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 56, 30, 462117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 20, 56, 30, 462043, tzinfo=utc)),
        ),
    ]
